version: "3.6"
services:
  viewpicam:
    image: cyr-ius/viewpicam:latest
    container_name: viewpicam
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    entrypoint:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000",
      ]
    environment:
      - SECRET_KEY=123456789
      - LOG_LEVEL=DEBUG
    ports:
      - 5000:5000/tcp
