version: "3.7"
services:
  viewpicam:
    image: ghcr.io/cyr-ius/viewpi-cam:latest
    container_name: viewpicam
    restart: unless-stopped
    environment:
      - SECRET_KEY=1234567890
    volumes:
      - static_volume:/app/static
      - ./medias:/app/media:rw
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - viewpicam
    volumes:
      - static_volume:/var/www/html/static
      - ./medias:/var/www/html/static/media
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80

volumes:
  static_volume:

# Onliner
# mkdir -p /mnt/data/media /mnt/data/h264 /mnt/data/macros /mnt/data/system
# docker run -d --privileged -p 80:8000 -e SECRET_KEY=1234567890 -v /mnt/data/media:/app/media -v /mnt/data/system:/app/system --name viewpicam ghcr.io/cyr-ius/viewpi-cam:latest
# docker logs viewpicam -f
