---
services:
  backend:
    image: cyr-ius/backend:armhf-latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - /media/data/viewpicam/backend/data:/app/data
  frontend:
    image: cyr-ius/frontend:armhf-latest
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - /media/data/viewpicam/backend/data:/usr/share/nginx/html/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
