---
services:
  backend:
    image: cyr-ius/viewpicam:armhf-latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - static_volume:/app/app/media
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
  frontend:
    image: frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/media
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80

volumes:
  static_volume:
