version: "3.6"
services:
  viewpicam:
    image: viewpicam:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile    
    container_name: viewpicam
    restart: unless-stopped
    environment:
      - SALT=123456789
      - SECRET_KEY=123456789
    ports:
      - 8000:8000/tcp
    volumes:
      - static_volume:/app/static
      - ./medias:/app/media:rw      
      - /opt/vc:/opt/vc
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - viewpicam
    volumes:
      - static_volume:/var/www/html/static
      - ./medias:/var/www/html/static/media
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro   
    ports:
      - 80:80

volumes:
  static_volume:  