name: Create release
on:
  push:
    tags:
      - "v*.*.*" # Push events to matching i.e. 1.0.0, 4.0.1
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
  publish:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-publish.yml

  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: Overwrite Version.txt file
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: .version
          write-mode: overwrite
          contents: "app_version:${{ steps.tagger.outputs.tag }}"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
